general.import = [
    "~/config/alacritty/themes/themes/catppuccin_macchiato.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5

decorations = "Full"
#decorations = "None"

# opacity = 0.7 
blur = true

#option_as_alt = "Both"

[font]
normal.family = "Hack Nerd Font Mono"

# size = 10.5
size = 9.5

[keyboard]
bindings = [
{ key = "v", mods = "Control", action = "Paste" },
]

[scrolling]
history = 10000  # Number of lines to keep in scrollback
multiplier = 3   # Speed of scrolling (optional)
